### PR TITLE
[RFC] Migration to v4.14.75-ltsi/rcar-3.9.2

### PR DESCRIPTION
**Pull request by otyshchenko1**
The following commits were dropped:

- clk: renesas: r8a7796: Remove clock that supplies i2c-dvfs
- clk: renesas: r8a7795: Remove clock that supplies i2c-dvfs
- clk: renesas: r8a7796: Remove clock that supplies all thermal sensors
- clk: renesas: r8a7795: Remove clock that supplies all thermal sensors
- drm/xen-zcopy: Add Xen zero-copy helper DRM driver
- drm/xen-front: Remove CMA support
- drm/xen-front: Add support for Xen PV display frontend
- drivers: flag buses which demand DMA configuration
- drm/simple-kms-helper: Plumb plane state to the enable hook
- drm: simple_kms_helper: Add mode_valid() callback support
- drm: Use srcu to protect drm_device.unplugged
- drm/simple_kms_helper: Fix NULL pointer dereference with no active CRTC
- Revert "drm/simple_kms_helper: Fix NULL pointer dereference with no active CRTC"
- Revert "drm: Use srcu to protect drm_device.unplugged"
- Revert "drm: simple_kms_helper: Add mode_valid() callback support"
- Revert "drm/simple-kms-helper: Plumb plane state to the enable hook"
- Revert "drivers: flag buses which demand DMA configuration"
- Revert "drm/xen-front: Add support for Xen PV display frontend"
- Revert "drm/xen-front: Remove CMA support"
- Revert "drm/xen-zcopy: Add Xen zero-copy helper DRM driver"
- Input: xen-kbdfront - fix multi-touch XenStore node's locations
- drm: rcar-du: Do not assume VSP has IOMMU
- drm/xen-zcopy: Add Xen zero-copy helper DRM driver
- Revert "drm: rcar-du: Do not assume VSP has IOMMU"
- Revert "drm/xen-zcopy: Add Xen zero-copy helper DRM driver"
- drm: rcar-du: Set the DMA coherent mask for the DU device
- xen/balloon: fix balloon initialization for PVH Dom0
- dmaengine: sh: rcar-dmac: Should not stop the DMAC by rcar_dmac_sync_tcr()
- dmaengine: sh: rcar-dmac: Add dma_pause operation
- dmaengine: sh: rcar-dmac: add a new function to clear CHCR.DE with barrier
- dmaengine: sh: rcar-dmac: avoid to write CHCR.TE to 1 if TCR is set to 0

The new one:
https://github.com/xen-troops/linux/commit/d2a3393e6ca4dbca2ca80927345ac0becf9cc820

!!! Important. Please note, the following patches should be removed from "recipes-domd/domd-image-weston/files/meta-xt-prod-extra/recipes-kernel/linux/linux-renesas_%.bbappend" for ALL INTENDED products:
- 0008-soc-Extend-always-on-logic-to-H3-ES3.0.patch
- 0001-Revert-clk-renesas-r8a7795-Remove-clock-that-supplie.patch
- 0002-Revert-clk-renesas-r8a7796-Remove-clock-that-supplie.patch
- 0003-Revert-clk-renesas-r8a7795-Remove-clock-that-supplie.patch
- 0004-Revert-clk-renesas-r8a7796-Remove-clock-that-supplie.patch

### CODE REVIEW

**Comment by andr2000** [comment]
I have an impression that 
> [HACK?]rcar_du_vs: zero-out sg_tables on plane duplication
had to be fixed by Renesas by now, but not sure

**Comment by otyshchenko1** [comment]
Update: already built tested.

+ new patch: 
https://github.com/xen-troops/linux/pull/63/commits/e0a203f2e4f6bbafde6aeecdee6b29ebeed02c5c

**Comment by otyshchenko1** [comment]
Update:
please see corresponding PR https://github.com/xen-troops/meta-xt-prod-gen3-test/pull/111

**Comment by otyshchenko1** [comment]
I understand your point, if we decide to go this way, we have to change device trees for "all supported machines" in "all supported Xen 4.12 products". Is it worth doing that?

**Comment by otyshchenko1** [comment]
The new corresponding PR is:
https://github.com/xen-troops/meta-xt-prod-gen3-test/pull/112

**Pull request merged**
