### PR TITLE
Xen troops pv sound for android - updates and minor fixes

### PR DESCRIPTION
**Pull request by andr2000**

### CODE REVIEW

**Comment by rshym** [comment]
Successfully tested by
```
console:/ # tinyplay /data/48000_16_2ch.wav
```

**Review by rshym — APPROVED** [review]

**Comment by arminn** [comment]
@andr2000 merge ?

**Comment by arminn** [comment]
@rshym it looks like we need to close it without merge, since  android-4.14-q-release-master is old and there is no chance/intention to test it

**Comment by rshym** [comment]
Closed as outdated.

**Pull request closed without merging**
