### PR TITLE
"Power domain maintenance" updates from v4.9/rcar-3.5.9 branch 

### PR DESCRIPTION
**Pull request by otyshchenko1**
These patches were cherry-picked from v4.9/rcar-3.5.9 branch to be aligned with PR to Xen which turns on A3xx power domains some IPMMU caches belong to. Without these patches Linux will disable all "unused" from its point of view power domains, where A3xx power domains are among them.

This PR should go in with the following PRs:
IPMMU-VMSA updates
https://github.com/xen-troops/xen/pull/105

dom0.dts/domd.dts: Remove "power-domains" property from SDHI2 node
https://github.com/xen-troops/meta-xt-prod-ces2018/pull/151

### CODE REVIEW

**Comment by aanisov** [comment]
I'm not really sure XEN is the right place to manage power domains.

**Comment by otyshchenko1** [comment]
On the whole I agree with you. I have added description to the newly created file in Xen's PR:
 "Some platform specific stuff for the IPMMU-VMSA which preferably should be moved out of Xen."
But I didn't think out something better. Maybe, you have some pointer what is the right place to manage power domains the several IPMMU caches belongs to?

You have two possible candidates:
1. In U-Boot? We don't patch U-Boot at all, we pull it from Renesas github. Modifying U-Boot means that we will have to maintain it as well.
2. In ARM-TF? It doesn't parse device tree to recognize what IPMMU caches are going to be used, what MMIO ranges they have, etc, in order to turn them on. We will have to hardcore everything in ARM-TF then. Personally, I find this way too difficult to maintain.

**Comment by otyshchenko1** [comment]
ping...

**Comment by aanisov** [comment]
`Reviewed-by: Andrii Anisov <andrii_anisov@epam.com>`

**Comment by otyshchenko1** [comment]
I am closing this PR, an actual PR is:
https://github.com/xen-troops/linux/pull/35

**Pull request closed without merging**
